services:
  application:
    container_name: dpide
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:dpide
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD:
    volumes:
      - /tmp # 영구 저장을 하지 않는 임시 디렉토리 사용

  h2:
    container_name: h2db
    image: oscarfonts/h2
    environment:
      - H2_OPTIONS=-webAllowOthers -tcpAllowOthers -ifNotExists
    ports:
      - 1521:1521
      - 8081:81

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/app.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - application