spring:
  application:
    name: dpide

  datasource:
    url: jdbc:mysql://mysql:3306/dpide_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: true

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  issuer: dpide
  secret_key:
