-- -- User 데이터
-- INSERT INTO users (id, email, password, nickname, created_at, updated_at) VALUES
--     (1, 'user1@example.com', 'password1', 'User One', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     (2, 'user2@example.com', 'password2', 'User Two', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     (3, 'user3@example.com', 'password3', 'User Three', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
-- -- Project 데이터
-- INSERT INTO projects (id, name, description, language, created_at, updated_at, user_id) VALUES
--     (1, 'Project A', 'Java backend project', 'Java', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
--     (2, 'Project B', 'Python AI project', 'Python', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
--     (3, 'Project C', 'Full stack web development', 'JavaScript', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3);
--
-- -- File 데이터
-- INSERT INTO files (id, name, extension, path, project_id, parent_id, created_at, updated_at) VALUES
--     (1, 'Main.java', 'java', '/src', 1, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     (2, 'App.py', 'py', '/src', 2, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
--     (3, 'index.js', 'js', '/src', 3, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
--
-- -- Chat 데이터
-- INSERT INTO chats (id, content, project_id, user_id, created_at) VALUES
--     (1, 'Chat for Project A', 1, 1, CURRENT_TIMESTAMP),
--     (2, 'Discussion on Project B', 2, 2, CURRENT_TIMESTAMP),
--     (3, 'Feedback on Project C', 3, 3, CURRENT_TIMESTAMP);
--
-- -- ProjectUser 데이터
-- INSERT INTO project_users (id, project_id, user_id, role, created_at) VALUES
--     (1, 1, 1, 'Admin', CURRENT_TIMESTAMP),
--     (2, 2, 2, 'Member', CURRENT_TIMESTAMP),
--     (3, 3, 3, 'Viewer', CURRENT_TIMESTAMP);
